language: php
php:
- 7.1.9
cache:
  directories:
  - $HOME/.composer/cache/files
install:
- composer install --no-scripts --prefer-dist
jobs:
  include:
  - stage: Code style
    script: ./build/codestyle.sh
  - stage: Testing
    script: ./build/test.sh
