<?php

return [
    /*
   |--------------------------------------------------------------------------
   | Schema definition files
   |--------------------------------------------------------------------------
   |
   | This package can generate a schema for you from multiple definition files.
   | Queries, Types and Mutations should always live in a seperate folder.
   | Here you can define the paths that should be imported, relative to your base path
   |
   */
    'schema_paths' => [
        'mutations' => 'app/Http/GraphQL/Mutations',
        'queries' => 'app/Http/GraphQL/Queries',
        'types' => 'app/Http/GraphQL/Types',
    ],

    /*
   |--------------------------------------------------------------------------
   | Use authorization for queries and mutations
   |--------------------------------------------------------------------------
   |
   | When this option is enabled, lighthouse-utils will place the @can directive
   | after every query and mutation. The permissions is generated by the action
   | and the model name.
   |
   */
    'authorization' => env('LIGHTHOUSE_UTILS_AUTHORIZATION', false),
];
