<?php

namespace DeInternetJongens\LighthouseUtils\Tests\Unit\Generators\Classes;

use DeInternetJongens\LighthouseUtils\Generators\Classes\ParseDefinitions;
use DeInternetJongens\LighthouseUtils\Tests\Unit\TestCase;

class ParseDefinitionsTest extends TestCase
{
    /** @var ParseDefinitions */
    private $definitionsParser;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->definitionsParser = new ParseDefinitions();
    }

    public function testGetGraphqlDefinitionFilePaths()
    {
        $paths = [
            'mutations' => '../../../../tests/Unit/Generators/files/schema/Mutations',
            'queries' => '../../../../tests/Unit/Generators/files/schema/Queries',
        ];

        $mutationFiles = $this->definitionsParser->getGraphqlDefinitionFilePaths($paths['mutations']);
        $queryFiles = $this->definitionsParser->getGraphqlDefinitionFilePaths($paths['queries']);

        $this->assertCount(1, $mutationFiles);
        $this->assertCount(1, $queryFiles);
    }

    public function testParseCustomQueriesFrom()
    {
        $paths = [
            'mutations' => '../../../../tests/Unit/Generators/files/schema/Mutations',
            'queries' => '../../../../tests/Unit/Generators/files/schema/Queries',
        ];

        $queries = $this->definitionsParser->parseCustomQueriesFrom($paths['queries']);

        $this->assertCount(2, $queries);
        $this->assertEquals(
            '    test(id: ID! @eq): Model! @can(if: "testPermission", model: "User")  @find(model: "Model")',
            $queries[0]
        );
        $this->assertEquals(
            '    testTwo(id: ID! @eq): Model! @can(if: "testPermission", model: "User")  @find(model: "Model")',
            $queries[1]
        );
    }

    public function testParseCustomMutationsFrom()
    {
        $paths = [
            'mutations' => '../../../../tests/Unit/Generators/files/schema/Mutations',
            'queries' => '../../../../tests/Unit/Generators/files/schema/Queries',
        ];

        $mutations = $this->definitionsParser->parseCustomMutationsFrom($paths['mutations']);

        $this->assertCount(2, $mutations);
        $this->assertEquals(
            '    test(input: testInput!): Model @create(model: "Model") @can(if: "testPermission", model: "User")',
            $mutations[0]
        );
        $this->assertEquals(
            '    secondTest(input: testInput!): Model @create(model: "Model") @can(if: "testPermission", model: "User")',
            $mutations[1]
        );
    }
}
